// Bible or Cap Game Data - 100+ Statements
const capStatements = [
    // REAL Bible verses (60 real ones)
    { text: "A man's stomach shall be satisfied from the fruit of his mouth.", isReal: true, reference: "Proverbs 18:20" },
    { text: "Iron sharpens iron, and one man sharpens another.", isReal: true, reference: "Proverbs 27:17" },
    { text: "The Lord is my shepherd; I shall not want.", isReal: true, reference: "Psalm 23:1" },
    { text: "Jesus wept.", isReal: true, reference: "John 11:35" },
    { text: "Love is patient, love is kind.", isReal: true, reference: "1 Corinthians 13:4" },
    { text: "In the beginning was the Word, and the Word was with God.", isReal: true, reference: "John 1:1" },
    { text: "The fear of the Lord is the beginning of wisdom.", isReal: true, reference: "Proverbs 9:10" },
    { text: "Where two or three gather in my name, there am I with them.", isReal: true, reference: "Matthew 18:20" },
    { text: "Greater love has no one than this: to lay down one's life for one's friends.", isReal: true, reference: "John 15:13" },
    { text: "Do not worry about tomorrow, for tomorrow will worry about itself.", isReal: true, reference: "Matthew 6:34" },
    { text: "The Lord gave, and the Lord has taken away; blessed be the name of the Lord.", isReal: true, reference: "Job 1:21" },
    { text: "Be still, and know that I am God.", isReal: true, reference: "Psalm 46:10" },
    { text: "The righteous person may have many troubles, but the Lord delivers him from them all.", isReal: true, reference: "Psalm 34:19" },
    { text: "A gentle answer turns away wrath, but a harsh word stirs up anger.", isReal: true, reference: "Proverbs 15:1" },
    { text: "Trust in the Lord with all your heart and lean not on your own understanding.", isReal: true, reference: "Proverbs 3:5" },
    { text: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you.", isReal: true, reference: "Jeremiah 29:11" },
    { text: "I can do all things through Christ who strengthens me.", isReal: true, reference: "Philippians 4:13" },
    { text: "The wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.", isReal: true, reference: "Romans 6:23" },
    { text: "For God so loved the world that he gave his one and only Son.", isReal: true, reference: "John 3:16" },
    { text: "Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.", isReal: true, reference: "Matthew 7:7" },
    { text: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", isReal: true, reference: "Psalm 34:18" },
    { text: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind.", isReal: true, reference: "Romans 12:2" },
    { text: "Come to me, all you who are weary and burdened, and I will give you rest.", isReal: true, reference: "Matthew 11:28" },
    { text: "Cast all your anxiety on him because he cares for you.", isReal: true, reference: "1 Peter 5:7" },
    { text: "The Lord is my light and my salvation—whom shall I fear?", isReal: true, reference: "Psalm 27:1" },
    { text: "No weapon forged against you will prevail.", isReal: true, reference: "Isaiah 54:17" },
    { text: "If God is for us, who can be against us?", isReal: true, reference: "Romans 8:31" },
    { text: "The joy of the Lord is your strength.", isReal: true, reference: "Nehemiah 8:10" },
    { text: "But those who hope in the Lord will renew their strength. They will soar on wings like eagles.", isReal: true, reference: "Isaiah 40:31" },
    { text: "Do not be anxious about anything, but in every situation, by prayer and petition, present your requests to God.", isReal: true, reference: "Philippians 4:6" },
    { text: "The Lord will fight for you; you need only to be still.", isReal: true, reference: "Exodus 14:14" },
    { text: "Taste and see that the Lord is good; blessed is the one who takes refuge in him.", isReal: true, reference: "Psalm 34:8" },
    { text: "Whatever you do, work at it with all your heart, as working for the Lord.", isReal: true, reference: "Colossians 3:23" },
    { text: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you.", isReal: true, reference: "Joshua 1:9" },
    { text: "Let your light shine before others, that they may see your good deeds and glorify your Father in heaven.", isReal: true, reference: "Matthew 5:16" },
    { text: "The Lord bless you and keep you; the Lord make his face shine on you.", isReal: true, reference: "Numbers 6:24-25" },
    { text: "He heals the brokenhearted and binds up their wounds.", isReal: true, reference: "Psalm 147:3" },
    { text: "And we know that in all things God works for the good of those who love him.", isReal: true, reference: "Romans 8:28" },
    { text: "The Lord is gracious and compassionate, slow to anger and rich in love.", isReal: true, reference: "Psalm 145:8" },
    { text: "Do not be overcome by evil, but overcome evil with good.", isReal: true, reference: "Romans 12:21" },
    { text: "Submit yourselves, then, to God. Resist the devil, and he will flee from you.", isReal: true, reference: "James 4:7" },
    { text: "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!", isReal: true, reference: "2 Corinthians 5:17" },
    { text: "Above all, love each other deeply, because love covers over a multitude of sins.", isReal: true, reference: "1 Peter 4:8" },
    { text: "Blessed are the pure in heart, for they will see God.", isReal: true, reference: "Matthew 5:8" },
    { text: "Give thanks in all circumstances; for this is God's will for you in Christ Jesus.", isReal: true, reference: "1 Thessalonians 5:18" },
    { text: "The grass withers and the flowers fall, but the word of our God endures forever.", isReal: true, reference: "Isaiah 40:8" },
    { text: "Surely your goodness and love will follow me all the days of my life.", isReal: true, reference: "Psalm 23:6" },
    { text: "Do not let your hearts be troubled. You believe in God; believe also in me.", isReal: true, reference: "John 14:1" },
    { text: "Peace I leave with you; my peace I give you. I do not give to you as the world gives.", isReal: true, reference: "John 14:27" },
    { text: "For where two or three gather in my name, there am I with them.", isReal: true, reference: "Matthew 18:20" },
    { text: "The Lord is my rock, my fortress and my deliverer.", isReal: true, reference: "Psalm 18:2" },
    { text: "Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.", isReal: true, reference: "Ephesians 4:32" },
    { text: "Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, think about such things.", isReal: true, reference: "Philippians 4:8" },
    { text: "The tongue has the power of life and death.", isReal: true, reference: "Proverbs 18:21" },
    { text: "Humble yourselves before the Lord, and he will lift you up.", isReal: true, reference: "James 4:10" },
    { text: "But seek first his kingdom and his righteousness, and all these things will be given to you as well.", isReal: true, reference: "Matthew 6:33" },
    { text: "My grace is sufficient for you, for my power is made perfect in weakness.", isReal: true, reference: "2 Corinthians 12:9" },
    { text: "Train up a child in the way he should go; even when he is old he will not depart from it.", isReal: true, reference: "Proverbs 22:6" },
    { text: "Be alert and of sober mind. Your enemy the devil prowls around like a roaring lion.", isReal: true, reference: "1 Peter 5:8" },
    { text: "Rejoice always, pray continually, give thanks in all circumstances.", isReal: true, reference: "1 Thessalonians 5:16-18" },
    
    // FAKE verses (Cap!) - 50 fake ones
    { text: "Blessed are those who help themselves, for they shall prosper.", isReal: false, reference: "NOT IN BIBLE" },
    { text: "God works in mysterious ways.", isReal: false, reference: "NOT IN BIBLE (Common saying but not Scripture)" },
    { text: "Cleanliness is next to godliness.", isReal: false, reference: "NOT IN BIBLE (John Wesley quote)" },
    { text: "Money is the root of all evil.", isReal: false, reference: "NOT IN BIBLE (1 Tim 6:10 says 'LOVE of money')" },
    { text: "This too shall pass.", isReal: false, reference: "NOT IN BIBLE (Persian proverb)" },
    { text: "God helps those who help themselves.", isReal: false, reference: "NOT IN BIBLE (Ben Franklin)" },
    { text: "To thine own self be true.", isReal: false, reference: "Shakespeare (Hamlet), not Bible!" },
    { text: "Spare the rod, spoil the child.", isReal: false, reference: "NOT IN BIBLE (Proverbs 13:24 is similar but different)" },
    { text: "The Lord moves in mysterious ways.", isReal: false, reference: "NOT IN BIBLE (William Cowper poem)" },
    { text: "Hate the sin, love the sinner.", isReal: false, reference: "NOT IN BIBLE (St. Augustine)" },
    { text: "God will never give you more than you can handle.", isReal: false, reference: "NOT IN BIBLE (1 Cor 10:13 is about temptation only)" },
    { text: "Everything happens for a reason.", isReal: false, reference: "NOT IN BIBLE (Popular phrase)" },
    { text: "The lion shall lie down with the lamb.", isReal: false, reference: "NOT IN BIBLE (Isaiah 11:6 says 'wolf with lamb')" },
    { text: "Pride comes before the fall.", isReal: false, reference: "NOT IN BIBLE (Prov 16:18 says 'before destruction')" },
    { text: "An eye for an eye makes the whole world blind.", isReal: false, reference: "Gandhi, not Bible!" },
    { text: "God won't give you anything you can't handle.", isReal: false, reference: "NOT IN BIBLE (Misquote)" },
    { text: "When God closes a door, He opens a window.", isReal: false, reference: "NOT IN BIBLE (Popular saying)" },
    { text: "Let go and let God.", isReal: false, reference: "NOT IN BIBLE (AA slogan)" },
    { text: "The early bird gets the worm.", isReal: false, reference: "Proverb, NOT Bible!" },
    { text: "A penny saved is a penny earned.", isReal: false, reference: "Ben Franklin, not Bible!" },
    { text: "Honesty is the best policy.", isReal: false, reference: "NOT IN BIBLE (Common saying)" },
    { text: "What doesn't kill you makes you stronger.", isReal: false, reference: "Nietzsche, not Bible!" },
    { text: "Charity begins at home.", isReal: false, reference: "NOT IN BIBLE (Sir Thomas Browne)" },
    { text: "All roads lead to heaven.", isReal: false, reference: "NOT IN BIBLE (Contradicts John 14:6)" },
    { text: "We are all God's children.", isReal: false, reference: "NOT IN BIBLE (Only believers are called children of God)" },
    { text: "Once saved, always saved.", isReal: false, reference: "NOT IN BIBLE (Theological debate, not a verse)" },
    { text: "Forgive and forget.", isReal: false, reference: "NOT IN BIBLE (Bible says forgive, not forget)" },
    { text: "God only helps those who are faithful.", isReal: false, reference: "NOT IN BIBLE (God helps sinners too!)" },
    { text: "The bigger they are, the harder they fall.", isReal: false, reference: "NOT IN BIBLE (Common saying)" },
    { text: "Beauty is only skin deep.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Home is where the heart is.", isReal: false, reference: "NOT IN BIBLE (Pliny the Elder)" },
    { text: "Better late than never.", isReal: false, reference: "NOT IN BIBLE (Ancient proverb)" },
    { text: "Actions speak louder than words.", isReal: false, reference: "NOT IN BIBLE (Abraham Lincoln)" },
    { text: "You reap what you sow.", isReal: true, reference: "Galatians 6:7" },
    { text: "Two wrongs don't make a right.", isReal: false, reference: "NOT IN BIBLE (Common saying)" },
    { text: "When in Rome, do as the Romans do.", isReal: false, reference: "St. Augustine (not Bible!)" },
    { text: "Practice makes perfect.", isReal: false, reference: "NOT IN BIBLE (Common saying)" },
    { text: "Laughter is the best medicine.", isReal: false, reference: "NOT IN BIBLE (Proverbs 17:22 is similar)" },
    { text: "Blood is thicker than water.", isReal: false, reference: "NOT IN BIBLE (Medieval proverb)" },
    { text: "The proof is in the pudding.", isReal: false, reference: "NOT IN BIBLE (Old English proverb)" },
    { text: "You can't teach an old dog new tricks.", isReal: false, reference: "NOT IN BIBLE (Common saying)" },
    { text: "Birds of a feather flock together.", isReal: false, reference: "NOT IN BIBLE (English proverb)" },
    { text: "Where there's smoke, there's fire.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Don't count your chickens before they hatch.", isReal: false, reference: "NOT IN BIBLE (Aesop's Fables)" },
    { text: "A watched pot never boils.", isReal: false, reference: "NOT IN BIBLE (Benjamin Franklin)" },
    { text: "Fool me once, shame on you; fool me twice, shame on me.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Time heals all wounds.", isReal: false, reference: "NOT IN BIBLE (Ancient saying)" },
    { text: "Silence is golden.", isReal: false, reference: "NOT IN BIBLE (Ancient proverb)" },
    { text: "The best things in life are free.", isReal: false, reference: "NOT IN BIBLE (Song lyric)" },
    { text: "What goes around comes around.", isReal: false, reference: "NOT IN BIBLE (Karma concept)" },
    
    // NEW TRICKY REAL VERSES
    { text: "A feast is made for laughter, wine makes life merry, and money is the answer for everything.", isReal: true, reference: "Ecclesiastes 10:19" },
    { text: "Like a gold ring in a pig's snout is a beautiful woman who shows no discretion.", isReal: true, reference: "Proverbs 11:22" },
    { text: "If you find honey, eat just enough—too much of it, and you will vomit.", isReal: true, reference: "Proverbs 25:16" },
    { text: "Better to live on a corner of the roof than share a house with a quarrelsome wife.", isReal: true, reference: "Proverbs 21:9" },
    { text: "If a man loudly blesses his neighbor early in the morning, it will be taken as a curse.", isReal: true, reference: "Proverbs 27:14" },
    { text: "I wish those who unsettle you would emasculate themselves!", isReal: true, reference: "Galatians 5:12" },
    { text: "A living dog is better than a dead lion.", isReal: true, reference: "Ecclesiastes 9:4" },
    { text: "There is no one righteous, not even one.", isReal: true, reference: "Romans 3:10" },
    { text: "You brood of vipers, how can you who are evil say anything good?", isReal: true, reference: "Matthew 12:34" },
    { text: "It is better to go to a house of mourning than to go to a house of feasting.", isReal: true, reference: "Ecclesiastes 7:2" },
    { text: "The sleep of a laborer is sweet, whether he eats little or much.", isReal: true, reference: "Ecclesiastes 5:12" },
    { text: "As a dog returns to its vomit, so fools repeat their folly.", isReal: true, reference: "Proverbs 26:11" },
    { text: "Do not answer a fool according to his folly, or you yourself will be just like him.", isReal: true, reference: "Proverbs 26:4" },
    { text: "Answer a fool according to his folly, or he will be wise in his own eyes.", isReal: true, reference: "Proverbs 26:5" },
    { text: "If your right eye causes you to stumble, gouge it out and throw it away.", isReal: true, reference: "Matthew 5:29" },
    { text: "It is easier for a camel to go through the eye of a needle than for someone who is rich to enter the kingdom of God.", isReal: true, reference: "Matthew 19:24" },
    { text: "Do not give dogs what is sacred; do not throw your pearls to pigs.", isReal: true, reference: "Matthew 7:6" },
    { text: "He who hates his life in this world will keep it for eternal life.", isReal: true, reference: "John 12:25" },
    { text: "Jacob I loved, but Esau I hated.", isReal: true, reference: "Romans 9:13" },
    { text: "I have seen everything in this meaningless life, including the righteous perishing in their righteousness and the wicked living long in their wickedness.", isReal: true, reference: "Ecclesiastes 7:15" },

    // NEW TRICKY FAKE VERSES (Sound Religious/Wise)
    { text: "Moderation in all things.", isReal: false, reference: "NOT IN BIBLE (Aristotle/Hesiod)" },
    { text: "Idle hands are the devil's workshop.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Confession is good for the soul.", isReal: false, reference: "NOT IN BIBLE (Scottish Proverb)" },
    { text: "The road to hell is paved with good intentions.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Man proposes, God disposes.", isReal: false, reference: "NOT IN BIBLE (Thomas a Kempis)" },
    { text: "A family that prays together stays together.", isReal: false, reference: "NOT IN BIBLE (Slogan)" },
    { text: "The eyes are the window to the soul.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "God is in the details.", isReal: false, reference: "NOT IN BIBLE (Mies van der Rohe)" },
    { text: "Love is blind.", isReal: false, reference: "NOT IN BIBLE (Chaucer/Shakespeare)" },
    { text: "To err is human, to forgive divine.", isReal: false, reference: "NOT IN BIBLE (Alexander Pope)" },
    { text: "All things in moderation.", isReal: false, reference: "NOT IN BIBLE (Greek Proverb)" },
    { text: "The seven deadly sins.", isReal: false, reference: "NOT IN BIBLE (Catholic Tradition)" },
    { text: "Three wise men visited Jesus.", isReal: false, reference: "NOT IN BIBLE (Bible says 'Magi', doesn't say 3)" },
    { text: "Jonah was swallowed by a whale.", isReal: false, reference: "NOT IN BIBLE (Bible says 'huge fish')" },
    { text: "Eve ate an apple.", isReal: false, reference: "NOT IN BIBLE (Bible says 'fruit')" },
    { text: "God helps those who help themselves.", isReal: false, reference: "NOT IN BIBLE (Ben Franklin)" },
    { text: "Cleanliness is next to godliness.", isReal: false, reference: "NOT IN BIBLE (John Wesley)" },
    { text: "Money is the root of all evil.", isReal: false, reference: "NOT IN BIBLE (1 Tim 6:10 says 'LOVE of money')" },
    { text: "Do your best and let God do the rest.", isReal: false, reference: "NOT IN BIBLE (Ben Carson/Proverb)" },
    { text: "When praises go up, blessings come down.", isReal: false, reference: "NOT IN BIBLE (Song lyric)" },
    { text: "If you want to make God laugh, tell him your plans.", isReal: false, reference: "NOT IN BIBLE (Woody Allen)" },
    { text: "God don't like ugly.", isReal: false, reference: "NOT IN BIBLE (Common saying)" },
    { text: "Prayer changes things.", isReal: false, reference: "NOT IN BIBLE (Slogan)" },
    { text: "The devil made me do it.", isReal: false, reference: "NOT IN BIBLE (Flip Wilson)" },
    // --- HARD MODE: REAL VERSES (Obscure, Weird, or Specific) ---
    { text: "A quarrelsome wife is like the dripping of a leaky roof in a rainstorm.", isReal: true, reference: "Proverbs 27:15" },
    { text: "If you mock the poor, you insult their Creator.", isReal: true, reference: "Proverbs 17:5" },
    { text: "Gray hair is a crown of splendor; it is attained in the way of righteousness.", isReal: true, reference: "Proverbs 16:31" },
    { text: "A person's own folly leads to their ruin, yet their heart rages against the Lord.", isReal: true, reference: "Proverbs 19:3" },
    { text: "Even a fool who keeps silent is considered wise.", isReal: true, reference: "Proverbs 17:28" },
    { text: "Do not listen to your prophets, your diviners, your interpreters of dreams, your mediums or your sorcerers.", isReal: true, reference: "Jeremiah 27:9" },
    { text: "Cursed is the one who trusts in man, who draws strength from mere flesh.", isReal: true, reference: "Jeremiah 17:5" },
    { text: "The heart is deceitful above all things and beyond cure. Who can understand it?", isReal: true, reference: "Jeremiah 17:9" },
    { text: "I am the Lord, the God of all mankind. Is anything too hard for me?", isReal: true, reference: "Jeremiah 32:27" },
    { text: "Do not seek revenge or bear a grudge against anyone among your people.", isReal: true, reference: "Leviticus 19:18" },
    { text: "You shall not tattoo any marks on you: I am the Lord.", isReal: true, reference: "Leviticus 19:28" },
    { text: "Do not mate different kinds of animals.", isReal: true, reference: "Leviticus 19:19" },
    { text: "Do not plant your field with two kinds of seed.", isReal: true, reference: "Leviticus 19:19" },
    { text: "Do not wear clothing woven of two kinds of material.", isReal: true, reference: "Leviticus 19:19" },
    { text: "When you reap the harvest of your land, do not reap to the very edges of your field.", isReal: true, reference: "Leviticus 19:9" },
    { text: "Do not hold back the wages of a hired worker overnight.", isReal: true, reference: "Leviticus 19:13" },
    { text: "Do not curse the deaf or put a stumbling block in front of the blind.", isReal: true, reference: "Leviticus 19:14" },
    { text: "Stand up in the presence of the aged, show respect for the elderly.", isReal: true, reference: "Leviticus 19:32" },
    { text: "The foreigner residing among you must be treated as your native-born.", isReal: true, reference: "Leviticus 19:34" },
    { text: "Do not use dishonest standards when measuring length, weight or quantity.", isReal: true, reference: "Leviticus 19:35" },
    { text: "If a man commits adultery with another man's wife, both the adulterer and the adulteress are to be put to death.", isReal: true, reference: "Leviticus 20:10" },
    { text: "A man who sleeps with his father’s wife has dishonored his father.", isReal: true, reference: "Leviticus 20:11" },
    { text: "If a man sleeps with his daughter-in-law, both of them are to be put to death.", isReal: true, reference: "Leviticus 20:12" },
    { text: "If a man lies with a male as with a woman, both of them have committed an abomination.", isReal: true, reference: "Leviticus 20:13" },
    { text: "If a man marries both a woman and her mother, it is wicked.", isReal: true, reference: "Leviticus 20:14" },
    { text: "If a man has sexual relations with an animal, he is to be put to death.", isReal: true, reference: "Leviticus 20:15" },
    { text: "If a woman approaches an animal to have sexual relations with it, kill both the woman and the animal.", isReal: true, reference: "Leviticus 20:16" },
    { text: "Do not eat any meat with the blood still in it.", isReal: true, reference: "Leviticus 19:26" },
    { text: "Do not cut the hair at the sides of your head or clip off the edges of your beard.", isReal: true, reference: "Leviticus 19:27" },
    { text: "Turn to me and be saved, all you ends of the earth.", isReal: true, reference: "Isaiah 45:22" },
    { text: "I form the light and create darkness, I bring prosperity and create disaster.", isReal: true, reference: "Isaiah 45:7" },
    { text: "Woe to those who call evil good and good evil.", isReal: true, reference: "Isaiah 5:20" },
    { text: "The wolf and the lamb will feed together, and the lion will eat straw like the ox.", isReal: true, reference: "Isaiah 65:25" },
    { text: "As the heavens are higher than the earth, so are my ways higher than your ways.", isReal: true, reference: "Isaiah 55:9" },
    { text: "All of us have become like one who is unclean, and all our righteous acts are like filthy rags.", isReal: true, reference: "Isaiah 64:6" },
    { text: "Can a mother forget the baby at her breast and have no compassion on the child she has borne?", isReal: true, reference: "Isaiah 49:15" },
    { text: "See, I have engraved you on the palms of my hands.", isReal: true, reference: "Isaiah 49:16" },
    { text: "How beautiful on the mountains are the feet of those who bring good news.", isReal: true, reference: "Isaiah 52:7" },
    { text: "He was pierced for our transgressions, he was crushed for our iniquities.", isReal: true, reference: "Isaiah 53:5" },
    { text: "We all, like sheep, have gone astray, each of us has turned to our own way.", isReal: true, reference: "Isaiah 53:6" },
    { text: "For the foolishness of God is wiser than human wisdom.", isReal: true, reference: "1 Corinthians 1:25" },
    { text: "God chose the foolish things of the world to shame the wise.", isReal: true, reference: "1 Corinthians 1:27" },
    { text: "Do not deceive yourselves. If any of you think you are wise by the standards of this age, you should become 'fools' so that you may become wise.", isReal: true, reference: "1 Corinthians 3:18" },
    { text: "Do you not know that you are God’s temple and that God’s Spirit dwells in you?", isReal: true, reference: "1 Corinthians 3:16" },
    { text: "I have the right to do anything, you say—but not everything is beneficial.", isReal: true, reference: "1 Corinthians 6:12" },
    { text: "Flee from sexual immorality. All other sins a person commits are outside the body.", isReal: true, reference: "1 Corinthians 6:18" },
    { text: "Knowledge puffs up while love builds up.", isReal: true, reference: "1 Corinthians 8:1" },
    { text: "If I speak in the tongues of men or of angels, but do not have love, I am only a resounding gong or a clanging cymbal.", isReal: true, reference: "1 Corinthians 13:1" },
    { text: "When I was a child, I talked like a child, I thought like a child, I reasoned like a child.", isReal: true, reference: "1 Corinthians 13:11" },
    { text: "And now these three remain: faith, hope and love. But the greatest of these is love.", isReal: true, reference: "1 Corinthians 13:13" },
    { text: "For as in Adam all die, so in Christ all will be made alive.", isReal: true, reference: "1 Corinthians 15:22" },
    { text: "Bad company corrupts good character.", isReal: true, reference: "1 Corinthians 15:33" },
    { text: "Where, O death, is your victory? Where, O death, is your sting?", isReal: true, reference: "1 Corinthians 15:55" },
    { text: "Be on your guard; stand firm in the faith; be courageous; be strong.", isReal: true, reference: "1 Corinthians 16:13" },
    { text: "We live by faith, not by sight.", isReal: true, reference: "2 Corinthians 5:7" },
    { text: "God loves a cheerful giver.", isReal: true, reference: "2 Corinthians 9:7" },
    { text: "For when I am weak, then I am strong.", isReal: true, reference: "2 Corinthians 12:10" },
    { text: "Greet one another with a holy kiss.", isReal: true, reference: "2 Corinthians 13:12" },
    { text: "There is neither Jew nor Gentile, neither slave nor free, nor is there male and female, for you are all one in Christ Jesus.", isReal: true, reference: "Galatians 3:28" },
    { text: "It is for freedom that Christ has set us free.", isReal: true, reference: "Galatians 5:1" },
    { text: "The fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control.", isReal: true, reference: "Galatians 5:22-23" },
    { text: "Bear one another's burdens, and so fulfill the law of Christ.", isReal: true, reference: "Galatians 6:2" },
    { text: "Do not be deceived: God cannot be mocked.", isReal: true, reference: "Galatians 6:7" },
    { text: "Let us not become weary in doing good.", isReal: true, reference: "Galatians 6:9" },
    { text: "For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God.", isReal: true, reference: "Ephesians 2:8" },
    { text: "For we are God’s handiwork, created in Christ Jesus to do good works.", isReal: true, reference: "Ephesians 2:10" },
    { text: "Be angry and do not sin; do not let the sun go down on your anger.", isReal: true, reference: "Ephesians 4:26" },
    { text: "Do not let any unwholesome talk come out of your mouths.", isReal: true, reference: "Ephesians 4:29" },
    { text: "Get rid of all bitterness, rage and anger, brawling and slander, along with every form of malice.", isReal: true, reference: "Ephesians 4:31" },
    { text: "Wake up, sleeper, rise from the dead, and Christ will shine on you.", isReal: true, reference: "Ephesians 5:14" },
    { text: "Wives, submit yourselves to your own husbands as you do to the Lord.", isReal: true, reference: "Ephesians 5:22" },
    { text: "Husbands, love your wives, just as Christ loved the church.", isReal: true, reference: "Ephesians 5:25" },
    { text: "Children, obey your parents in the Lord, for this is right.", isReal: true, reference: "Ephesians 6:1" },
    { text: "Put on the full armor of God, so that you can take your stand against the devil’s schemes.", isReal: true, reference: "Ephesians 6:11" },
    { text: "For our struggle is not against flesh and blood, but against the rulers, against the authorities.", isReal: true, reference: "Ephesians 6:12" },
    { text: "To live is Christ and to die is gain.", isReal: true, reference: "Philippians 1:21" },
    { text: "Do nothing out of selfish ambition or vain conceit.", isReal: true, reference: "Philippians 2:3" },
    { text: "Do everything without grumbling or arguing.", isReal: true, reference: "Philippians 2:14" },
    { text: "I press on toward the goal to win the prize for which God has called me heavenward.", isReal: true, reference: "Philippians 3:14" },
    { text: "Set your minds on things above, not on earthly things.", isReal: true, reference: "Colossians 3:2" },
    { text: "Husbands, love your wives and do not be harsh with them.", isReal: true, reference: "Colossians 3:19" },
    { text: "Let your conversation be always full of grace, seasoned with salt.", isReal: true, reference: "Colossians 4:6" },
    { text: "Pray without ceasing.", isReal: true, reference: "1 Thessalonians 5:17" },
    { text: "The one who calls you is faithful, and he will do it.", isReal: true, reference: "1 Thessalonians 5:24" },
    { text: "If a man will not work, he shall not eat.", isReal: true, reference: "2 Thessalonians 3:10" },
    { text: "Fight the good fight of the faith.", isReal: true, reference: "1 Timothy 6:12" },
    { text: "For the love of money is a root of all kinds of evil.", isReal: true, reference: "1 Timothy 6:10" },
    { text: "God has not given us a spirit of fear, but of power and of love and of a sound mind.", isReal: true, reference: "2 Timothy 1:7" },
    { text: "I have fought the good fight, I have finished the race, I have kept the faith.", isReal: true, reference: "2 Timothy 4:7" },
    { text: "All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness.", isReal: true, reference: "2 Timothy 3:16" },
    { text: "To the pure, all things are pure.", isReal: true, reference: "Titus 1:15" },
    { text: "Faith is the substance of things hoped for, the evidence of things not seen.", isReal: true, reference: "Hebrews 11:1" },
    { text: "Jesus Christ is the same yesterday and today and forever.", isReal: true, reference: "Hebrews 13:8" },
    { text: "Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds.", isReal: true, reference: "James 1:2" },
    { text: "Everyone should be quick to listen, slow to speak and slow to become angry.", isReal: true, reference: "James 1:19" },
    { text: "Faith by itself, if it is not accompanied by action, is dead.", isReal: true, reference: "James 2:17" },
    { text: "A double-minded man is unstable in all his ways.", isReal: true, reference: "James 1:8" },
    { text: "Draw near to God and He will draw near to you.", isReal: true, reference: "James 4:8" },
    { text: "The prayer of a righteous person is powerful and effective.", isReal: true, reference: "James 5:16" },
    { text: "Be self-controlled and alert. Your enemy the devil prowls around like a roaring lion.", isReal: true, reference: "1 Peter 5:8" },
    { text: "If we confess our sins, he is faithful and just and will forgive us our sins.", isReal: true, reference: "1 John 1:9" },
    { text: "Do not love the world or anything in the world.", isReal: true, reference: "1 John 2:15" },
    { text: "There is no fear in love. But perfect love drives out fear.", isReal: true, reference: "1 John 4:18" },
    { text: "We love because he first loved us.", isReal: true, reference: "1 John 4:19" },
    { text: "I know your deeds, that you are neither cold nor hot. I wish you were either one or the other!", isReal: true, reference: "Revelation 3:15" },
    { text: "So, because you are lukewarm—neither hot nor cold—I am about to spit you out of my mouth.", isReal: true, reference: "Revelation 3:16" },
    { text: "Behold, I stand at the door and knock.", isReal: true, reference: "Revelation 3:20" },
    { text: "He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain.", isReal: true, reference: "Revelation 21:4" },
    { text: "I am the Alpha and the Omega, the First and the Last, the Beginning and the End.", isReal: true, reference: "Revelation 22:13" },
    { text: "A cord of three strands is not quickly broken.", isReal: true, reference: "Ecclesiastes 4:12" },
    { text: "There is a time for everything, and a season for every activity under the heavens.", isReal: true, reference: "Ecclesiastes 3:1" },
    { text: "Cast your bread upon the waters, for you will find it after many days.", isReal: true, reference: "Ecclesiastes 11:1" },
    { text: "Remember your Creator in the days of your youth.", isReal: true, reference: "Ecclesiastes 12:1" },
    { text: "Fear God and keep his commandments, for this is the duty of all mankind.", isReal: true, reference: "Ecclesiastes 12:13" },
    { text: "My beloved is mine and I am his.", isReal: true, reference: "Song of Solomon 2:16" },
    { text: "Catch for us the foxes, the little foxes that ruin the vineyards.", isReal: true, reference: "Song of Solomon 2:15" },
    { text: "Many waters cannot quench love; rivers cannot sweep it away.", isReal: true, reference: "Song of Solomon 8:7" },
    { text: "Though your sins are like scarlet, they shall be as white as snow.", isReal: true, reference: "Isaiah 1:18" },
    { text: "Here I am. Send me!", isReal: true, reference: "Isaiah 6:8" },
    { text: "The people walking in darkness have seen a great light.", isReal: true, reference: "Isaiah 9:2" },
    { text: "For to us a child is born, to us a son is given.", isReal: true, reference: "Isaiah 9:6" },
    { text: "He will keep him in perfect peace, whose mind is stayed on You.", isReal: true, reference: "Isaiah 26:3" },
    { text: "But he was wounded for our transgressions, he was bruised for our iniquities.", isReal: true, reference: "Isaiah 53:5" },
    { text: "Arise, shine, for your light has come.", isReal: true, reference: "Isaiah 60:1" },
    { text: "The Spirit of the Sovereign Lord is on me, because the Lord has anointed me, to proclaim good news to the poor.", isReal: true, reference: "Isaiah 61:1" },
    { text: "Before I formed you in the womb I knew you.", isReal: true, reference: "Jeremiah 1:5" },
    { text: "Call to me and I will answer you and tell you great and unsearchable things you do not know.", isReal: true, reference: "Jeremiah 33:3" },
    { text: "His compassions never fail. They are new every morning; great is your faithfulness.", isReal: true, reference: "Lamentations 3:22-23" },
    { text: "By the skin of my teeth.", isReal: true, reference: "Job 19:20" },
    { text: "Fly in the ointment.", isReal: true, reference: "Ecclesiastes 10:1" },
    { text: "Blind guides.", isReal: true, reference: "Matthew 23:24" },
    { text: "Salt of the earth.", isReal: true, reference: "Matthew 5:13" },
    { text: "Faith moving mountains.", isReal: true, reference: "Matthew 17:20" },
    { text: "Touch not the Lord's anointed.", isReal: true, reference: "1 Samuel 26:9" },
    { text: "This is the day the Lord has made.", isReal: true, reference: "Psalm 118:24" },
    { text: "He who is without sin cast the first stone.", isReal: true, reference: "John 8:7" },
    { text: "Am I my brother's keeper?", isReal: true, reference: "Genesis 4:9" },
    { text: "The spirit is willing, but the flesh is weak.", isReal: true, reference: "Matthew 26:41" },
    { text: "Many are called, but few are chosen.", isReal: true, reference: "Matthew 22:14" },
    { text: "The truth shall set you free.", isReal: true, reference: "John 8:32" },
    { text: "My cup runneth over.", isReal: true, reference: "Psalm 23:5" },
    { text: "Valley of the shadow of death.", isReal: true, reference: "Psalm 23:4" },
    { text: "A land flowing with milk and honey.", isReal: true, reference: "Exodus 3:8" },
    { text: "Man shall not live by bread alone.", isReal: true, reference: "Matthew 4:4" },
    { text: "The love of money is the root of all evil.", isReal: true, reference: "1 Timothy 6:10" },
    { text: "Fight the good fight.", isReal: true, reference: "1 Timothy 6:12" },
    { text: "O death, where is thy sting?", isReal: true, reference: "1 Corinthians 15:55" },
    { text: "In the beginning God created the heavens and the earth.", isReal: true, reference: "Genesis 1:1" },
    { text: "Let there be light.", isReal: true, reference: "Genesis 1:3" },
    { text: "It is not good for the man to be alone.", isReal: true, reference: "Genesis 2:18" },
    { text: "Dust you are and to dust you will return.", isReal: true, reference: "Genesis 3:19" },
    { text: "Be fruitful and increase in number.", isReal: true, reference: "Genesis 1:28" },
    { text: "I set my rainbow in the clouds.", isReal: true, reference: "Genesis 9:13" },
    { text: "The Lord is my shepherd, I lack nothing.", isReal: true, reference: "Psalm 23:1" },
    { text: "He leads me beside quiet waters.", isReal: true, reference: "Psalm 23:2" },
    { text: "Create in me a pure heart, O God.", isReal: true, reference: "Psalm 51:10" },
    { text: "Open my lips, Lord, and my mouth will declare your praise.", isReal: true, reference: "Psalm 51:15" },
    { text: "How good and pleasant it is when God’s people live together in unity!", isReal: true, reference: "Psalm 133:1" },
    { text: "Your word is a lamp for my feet, a light on my path.", isReal: true, reference: "Psalm 119:105" },
    { text: "I have hidden your word in my heart that I might not sin against you.", isReal: true, reference: "Psalm 119:11" },
    { text: "Fear of the Lord is the beginning of knowledge.", isReal: true, reference: "Proverbs 1:7" },
    { text: "Trust in the Lord with all your heart.", isReal: true, reference: "Proverbs 3:5" },
    { text: "In all your ways submit to him, and he will make your paths straight.", isReal: true, reference: "Proverbs 3:6" },
    { text: "Above all else, guard your heart, for everything you do flows from it.", isReal: true, reference: "Proverbs 4:23" },
    { text: "A gentle answer turns away wrath.", isReal: true, reference: "Proverbs 15:1" },
    { text: "Pride goes before destruction.", isReal: true, reference: "Proverbs 16:18" },
    
    // --- HARD MODE: FAKE STATEMENTS (Sound convincing but aren't Bible) ---
    { text: "God helps those who help themselves.", isReal: false, reference: "NOT IN BIBLE (Ben Franklin)" },
    { text: "Cleanliness is next to godliness.", isReal: false, reference: "NOT IN BIBLE (John Wesley)" },
    { text: "Money is the root of all evil.", isReal: false, reference: "NOT IN BIBLE (It's the LOVE of money)" },
    { text: "This too shall pass.", isReal: false, reference: "NOT IN BIBLE (Persian Proverb)" },
    { text: "To thine own self be true.", isReal: false, reference: "NOT IN BIBLE (Shakespeare)" },
    { text: "Charity begins at home.", isReal: false, reference: "NOT IN BIBLE (Sir Thomas Browne)" },
    { text: "God works in mysterious ways.", isReal: false, reference: "NOT IN BIBLE (William Cowper hymm)" },
    { text: "Spare the rod and spoil the child.", isReal: false, reference: "NOT IN BIBLE (Samuel Butler)" },
    { text: "The eye is the window to the soul.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "A fool and his money are soon parted.", isReal: false, reference: "NOT IN BIBLE (Thomas Tusser)" },
    { text: "Early to bed and early to rise makes a man healthy, wealthy, and wise.", isReal: false, reference: "NOT IN BIBLE (Ben Franklin)" },
    { text: "Honesty is the best policy.", isReal: false, reference: "NOT IN BIBLE (Edwin Sandys)" },
    { text: "A penny saved is a penny earned.", isReal: false, reference: "NOT IN BIBLE (Ben Franklin)" },
    { text: "Hell hath no fury like a woman scorned.", isReal: false, reference: "NOT IN BIBLE (William Congreve)" },
    { text: "Practice makes perfect.", isReal: false, reference: "NOT IN BIBLE (Common Saying)" },
    { text: "The early bird catches the worm.", isReal: false, reference: "NOT IN BIBLE (William Camden)" },
    { text: "Actions speak louder than words.", isReal: false, reference: "NOT IN BIBLE (Abraham Lincoln)" },
    { text: "Birds of a feather flock together.", isReal: false, reference: "NOT IN BIBLE (William Turner)" },
    { text: "Don't count your chickens before they hatch.", isReal: false, reference: "NOT IN BIBLE (Aesop)" },
    { text: "Every cloud has a silver lining.", isReal: false, reference: "NOT IN BIBLE (John Milton)" },
    { text: "Fortune favors the bold.", isReal: false, reference: "NOT IN BIBLE (Latin Proverb)" },
    { text: "Ignorance is bliss.", isReal: false, reference: "NOT IN BIBLE (Thomas Gray)" },
    { text: "It's better to give than to receive.", isReal: true, reference: "Acts 20:35 (Wait! This IS real!)" }, 
    { text: "Knowledge is power.", isReal: false, reference: "NOT IN BIBLE (Francis Bacon)" },
    { text: "Laughter is the best medicine.", isReal: false, reference: "NOT IN BIBLE (Reader's Digest)" },
    { text: "Look before you leap.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "No pain, no gain.", isReal: false, reference: "NOT IN BIBLE (Jane Fonda/Proverb)" },
    { text: "Out of sight, out of mind.", isReal: false, reference: "NOT IN BIBLE (John Heywood)" },
    { text: "Patience is a virtue.", isReal: false, reference: "NOT IN BIBLE (Cato the Elder)" },
    { text: "Politeness costs nothing.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Rome wasn't built in a day.", isReal: false, reference: "NOT IN BIBLE (Medieval French Phrase)" },
    { text: "The pen is mightier than the sword.", isReal: false, reference: "NOT IN BIBLE (Edward Bulwer-Lytton)" },
    { text: "Time flies when you're having fun.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Time is money.", isReal: false, reference: "NOT IN BIBLE (Ben Franklin)" },
    { text: "Variety is the spice of life.", isReal: false, reference: "NOT IN BIBLE (William Cowper)" },
    { text: "When in Rome, do as the Romans do.", isReal: false, reference: "NOT IN BIBLE (St. Ambrose)" },
    { text: "Where there's a will, there's a way.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "You can't have your cake and eat it too.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "A smooth sea never made a skilled sailor.", isReal: false, reference: "NOT IN BIBLE (FDR)" },
    { text: "All good things must come to an end.", isReal: false, reference: "NOT IN BIBLE (Chaucer)" },
    { text: "All's fair in love and war.", isReal: false, reference: "NOT IN BIBLE (Francis Smedley)" },
    { text: "An apple a day keeps the doctor away.", isReal: false, reference: "NOT IN BIBLE (Welsh Proverb)" },
    { text: "April showers bring May flowers.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Ask me no questions, and I'll tell you no lies.", isReal: false, reference: "NOT IN BIBLE (Oliver Goldsmith)" },
    { text: "Beggar can't be choosers.", isReal: false, reference: "NOT IN BIBLE (John Heywood)" },
    { text: "Better safe than sorry.", isReal: false, reference: "NOT IN BIBLE (Samuel Lover)" },
    { text: "Curiosity killed the cat.", isReal: false, reference: "NOT IN BIBLE (Playwright Ben Jonson)" },
    { text: "Don't bite the hand that feeds you.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Don't judge a book by its cover.", isReal: false, reference: "NOT IN BIBLE (George Eliot)" },
    { text: "Don't put all your eggs in one basket.", isReal: false, reference: "NOT IN BIBLE (Cervantes)" },
    { text: "Easy come, easy go.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Every dog has its day.", isReal: false, reference: "NOT IN BIBLE (Shakespeare)" },
    { text: "Give credit where credit is due.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Good things come to those who wait.", isReal: false, reference: "NOT IN BIBLE (Violet Fane)" },
    { text: "Haste makes waste.", isReal: false, reference: "NOT IN BIBLE (John Heywood)" },
    { text: "He who laughs last, laughs best.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "History repeats itself.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "If at first you don't succeed, try, try again.", isReal: false, reference: "NOT IN BIBLE (Thomas Palmer)" },
    { text: "If you can't beat 'em, join 'em.", isReal: false, reference: "NOT IN BIBLE (Political saying)" },
    { text: "It takes two to tango.", isReal: false, reference: "NOT IN BIBLE (Song Lyric)" },
    { text: "Keep your friends close and your enemies closer.", isReal: false, reference: "NOT IN BIBLE (Sun Tzu)" },
    { text: "Kill them with kindness.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Let bygones be bygones.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Like father, like son.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Live and let live.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Necessity is the mother of invention.", isReal: false, reference: "NOT IN BIBLE (Plato)" },
    { text: "No news is good news.", isReal: false, reference: "NOT IN BIBLE (James I)" },
    { text: "One man's trash is another man's treasure.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Opposites attract.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Power corrupts; absolute power corrupts absolutely.", isReal: false, reference: "NOT IN BIBLE (Lord Acton)" },
    { text: "Strike while the iron is hot.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "The apple doesn't fall far from the tree.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "The end justifies the means.", isReal: false, reference: "NOT IN BIBLE (Machiavelli)" },
    { text: "The grass is always greener on the other side.", isReal: false, reference: "NOT IN BIBLE (Ovid)" },
    { text: "The more the merrier.", isReal: false, reference: "NOT IN BIBLE (John Heywood)" },
    { text: "The road to success is always under construction.", isReal: false, reference: "NOT IN BIBLE (Lily Tomlin)" },
    { text: "There is no such thing as a free lunch.", isReal: false, reference: "NOT IN BIBLE (Economics)" },
    { text: "Two heads are better than one.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "United we stand, divided we fall.", isReal: false, reference: "NOT IN BIBLE (Aesop)" },
    { text: "What you see is what you get.", isReal: false, reference: "NOT IN BIBLE (Flip Wilson)" },
    { text: "When the going gets tough, the tough get going.", isReal: false, reference: "NOT IN BIBLE (Joseph Kennedy)" },
    { text: "You are what you eat.", isReal: false, reference: "NOT IN BIBLE (Anthelme Brillat-Savarin)" },
    { text: "You can lead a horse to water, but you can't make him drink.", isReal: false, reference: "NOT IN BIBLE (John Heywood)" },
    { text: "You catch more flies with honey than with vinegar.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "You win some, you lose some.", isReal: false, reference: "NOT IN BIBLE (Idiom)" },
    { text: "The seven deadly sins are lust, gluttony, greed, sloth, wrath, envy, and pride.", isReal: false, reference: "NOT IN BIBLE (Catholic Theology)" },
    { text: "The three wise men were named Gaspar, Melchior, and Balthasar.", isReal: false, reference: "NOT IN BIBLE (Tradition, scripture doesn't name or number them)" },
    { text: "Mary Magdalene was a prostitute.", isReal: false, reference: "NOT IN BIBLE (Tradition, scripture doesn't say this)" },
    { text: "Paul fell off a horse on the road to Damascus.", isReal: false, reference: "NOT IN BIBLE (Acts 9 says he fell to the ground, no horse mentioned)" },
    { text: "Jonah was swallowed by a whale.", isReal: false, reference: "NOT IN BIBLE (Hebrew says 'Great Fish')" },
    { text: "Delilah cut Samson's hair.", isReal: false, reference: "NOT IN BIBLE (Judges 16:19 says she called a man to do it)" },
    { text: "Noah's Ark carried two of every kind of animal.", isReal: false, reference: "NOT IN BIBLE (Gen 7:2 says 7 pairs of clean animals)" },
    { text: "The forbidden fruit in Eden was an apple.", isReal: false, reference: "NOT IN BIBLE (Genesis just says 'fruit')" },
    { text: "Angels have halos and play harps on clouds.", isReal: false, reference: "NOT IN BIBLE (Artistic tradition)" },
    { text: "Satan rules over Hell.", isReal: false, reference: "NOT IN BIBLE (Hell is his punishment, not his kingdom)" },
    { text: "The Antichrist will be a specific person.", isReal: false, reference: "NOT IN BIBLE (1 John 2:18 says there are 'many antichrists')" },
    { text: "The rapture will happen before the tribulation.", isReal: false, reference: "NOT IN BIBLE (Highly debated theological interpretation)" },
    { text: "God wants you to be happy.", isReal: false, reference: "NOT IN BIBLE (God wants you to be holy)" },
    { text: "Love the sinner, hate the sin.", isReal: false, reference: "NOT IN BIBLE (St. Augustine / Gandhi)" },
    { text: "Elijah went to heaven in a chariot of fire.", isReal: false, reference: "NOT IN BIBLE (2 Kings 2:11 says a WHIRLWIND took him, the chariot just appeared)" },
    { text: "Jesus was born in a stable.", isReal: false, reference: "NOT IN BIBLE (Luke says 'manger' (feeding trough), could be a cave or lower floor of house)" },
    { text: "Kiss of death.", isReal: false, reference: "NOT IN BIBLE (Judas kissed Jesus, but phrase is idiomatic)" },
    { text: "Forbidden fruit.", isReal: false, reference: "NOT IN BIBLE (Concept is real, phrase is not in KJV)" },
    { text: "Moderation in all things.", isReal: false, reference: "NOT IN BIBLE (Terence)" },
    { text: "God helps those who help themselves.", isReal: false, reference: "NOT IN BIBLE (Algernon Sydney)" },
    { text: "This is the cross I have to bear.", isReal: false, reference: "NOT IN BIBLE (Idiomatic)" },
    { text: "Hate the sin, love the sinner.", isReal: false, reference: "NOT IN BIBLE (Gandhi)" },
    { text: "The Lion shall lie down with the Lamb.", isReal: false, reference: "NOT IN BIBLE (Isaiah 11:6 says Wolf and Lamb)" },
    { text: "Money is the root of all evil.", isReal: false, reference: "NOT IN BIBLE (1 Timothy 6:10 says LOVE of money)" },
    { text: "Prides comes before a fall.", isReal: false, reference: "NOT IN BIBLE (Proverbs 16:18 says Pride goes before destruction)" },
    { text: "Charity begins at home.", isReal: false, reference: "NOT IN BIBLE (Sir Thomas Browne)" },
    { text: "To thine own self be true.", isReal: false, reference: "NOT IN BIBLE (Hamlet)" },
    { text: "God works in mysterious ways.", isReal: false, reference: "NOT IN BIBLE (William Cowper)" },
    { text: "Cleanliness is next to godliness.", isReal: false, reference: "NOT IN BIBLE (John Wesley)" },
    { text: "Spare the rod and spoil the child.", isReal: false, reference: "NOT IN BIBLE (Samuel Butler)" },
    { text: "There but for the grace of God go I.", isReal: false, reference: "NOT IN BIBLE (John Bradford)" },
    { text: "All things must pass.", isReal: false, reference: "NOT IN BIBLE (George Harrison)" },
    { text: "Do unto others as you would have them do unto you.", isReal: true, reference: "Matthew 7:12 (Golden Rule IS Bible!)" },
    { text: "Confession is good for the soul.", isReal: false, reference: "NOT IN BIBLE (Scottish Proverb)" },
    { text: "A watched pot never boils.", isReal: false, reference: "NOT IN BIBLE (Ben Franklin)" },
];
